"""
scheduler.py — Camelot OS Report Bot
=====================================
Cron-based scheduler for automated report generation.

Schedule:
  - Monthly owner statements: 1st of each month at 06:00 EST
  - Weekly KPI dashboard:     Every Monday at 08:00 EST
  - Quarterly investor update: 1st of Jan / Apr / Jul / Oct at 07:00 EST

The scheduler uses the `schedule` library for in-process scheduling and
writes a PID file to allow external process management. It also supports
one-shot execution modes via CLI flags.

Usage:
    # Run the persistent scheduler daemon
    python scheduler.py --daemon

    # Run a specific report immediately (one-shot)
    python scheduler.py --run owner-statements
    python scheduler.py --run kpi-dashboard
    python scheduler.py --run investor-update [--year YYYY --quarter Q]

Author: Camelot OS
"""

from __future__ import annotations

import argparse
import logging
import os
import signal
import sys
import time
from datetime import date, datetime
from pathlib import Path
from typing import Optional

import schedule  # type: ignore

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------
LOG_LEVEL = os.getenv("LOG_LEVEL", "INFO").upper()
logging.basicConfig(
    level=getattr(logging, LOG_LEVEL, logging.INFO),
    format="%(asctime)s [%(levelname)s] %(name)s — %(message)s",
    handlers=[
        logging.StreamHandler(sys.stdout),
        logging.FileHandler(
            os.getenv("LOG_FILE", "logs/report_scheduler.log"),
            encoding="utf-8",
        ),
    ],
)
logger = logging.getLogger("report_bot.scheduler")

# ---------------------------------------------------------------------------
# Configuration from environment
# ---------------------------------------------------------------------------
OUTPUT_DIR: str = os.getenv("REPORT_OUTPUT_DIR", "output/reports")
ALERT_EMAIL: str = os.getenv("REPORT_ALERT_EMAIL", "dgoldoff@camelot.nyc")
SEND_EMAIL_ON_COMPLETION: bool = os.getenv("REPORT_EMAIL_DELIVERY", "true").lower() == "true"
PID_FILE: str = os.getenv("SCHEDULER_PID_FILE", "/tmp/camelot_report_scheduler.pid")

# Cron times (24h, EST — ensure server TZ is set to America/New_York or
# adjust to UTC offsets in production)
MONTHLY_STATEMENTS_TIME: str = os.getenv("MONTHLY_STATEMENTS_TIME", "06:00")
WEEKLY_KPI_TIME: str = os.getenv("WEEKLY_KPI_TIME", "08:00")
QUARTERLY_UPDATE_TIME: str = os.getenv("QUARTERLY_UPDATE_TIME", "07:00")

# Months that trigger a quarterly investor update
QUARTERLY_MONTHS: frozenset[int] = frozenset([1, 4, 7, 10])


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _ensure_dirs() -> None:
    """Create required directories if they do not exist."""
    Path(OUTPUT_DIR).mkdir(parents=True, exist_ok=True)
    log_dir = Path(os.getenv("LOG_FILE", "logs/report_scheduler.log")).parent
    log_dir.mkdir(parents=True, exist_ok=True)


def _write_pid() -> None:
    """Write current PID to file for external process management."""
    try:
        with open(PID_FILE, "w") as f:
            f.write(str(os.getpid()))
        logger.info("PID file written to %s (PID=%d)", PID_FILE, os.getpid())
    except OSError as exc:
        logger.warning("Could not write PID file: %s", exc)


def _remove_pid() -> None:
    """Remove PID file on clean shutdown."""
    try:
        if os.path.exists(PID_FILE):
            os.remove(PID_FILE)
    except OSError:
        pass


def _deliver_report(subject: str, pdf_path: str, recipients: list[str]) -> None:
    """
    Email the generated report to recipients.
    Falls back gracefully if SMTP is not configured.
    """
    if not SEND_EMAIL_ON_COMPLETION:
        logger.info("Email delivery disabled — skipping send for: %s", pdf_path)
        return

    smtp_host = os.getenv("SMTP_HOST")
    if not smtp_host:
        logger.warning("SMTP_HOST not set — cannot deliver report by email")
        return

    import smtplib
    import ssl
    from email import encoders
    from email.mime.base import MIMEBase
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText

    smtp_port = int(os.getenv("SMTP_PORT", "587"))
    smtp_user = os.getenv("SMTP_USER", "")
    smtp_pass = os.getenv("SMTP_PASSWORD", "")
    sender = os.getenv("SMTP_FROM", smtp_user or "reports@camelot.nyc")

    msg = MIMEMultipart()
    msg["From"] = sender
    msg["To"] = ", ".join(recipients)
    msg["Subject"] = subject

    body = (
        f"Please find attached the {subject} generated by Camelot OS.\n\n"
        f"Report file: {os.path.basename(pdf_path)}\n"
        f"Generated at: {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}\n\n"
        "This is an automated message from Camelot OS Report Bot.\n"
        "Camelot Property Management Services Corp — Confidential."
    )
    msg.attach(MIMEText(body, "plain"))

    # Attach PDF
    try:
        with open(pdf_path, "rb") as f:
            part = MIMEBase("application", "octet-stream")
            part.set_payload(f.read())
        encoders.encode_base64(part)
        part.add_header(
            "Content-Disposition",
            f"attachment; filename={os.path.basename(pdf_path)}",
        )
        msg.attach(part)
    except OSError as exc:
        logger.error("Failed to attach PDF %s: %s", pdf_path, exc)
        return

    try:
        context = ssl.create_default_context()
        with smtplib.SMTP(smtp_host, smtp_port) as server:
            server.ehlo()
            server.starttls(context=context)
            if smtp_user and smtp_pass:
                server.login(smtp_user, smtp_pass)
            server.sendmail(sender, recipients, msg.as_string())
        logger.info("Report emailed to %s — %s", recipients, subject)
    except smtplib.SMTPException as exc:
        logger.error("SMTP send failed for %s: %s", subject, exc)


# ---------------------------------------------------------------------------
# Scheduled job functions
# ---------------------------------------------------------------------------

def schedule_monthly_statements() -> None:
    """
    Generate owner statements for all properties.
    Runs on the 1st of each month at MONTHLY_STATEMENTS_TIME.
    """
    logger.info("=== Monthly Owner Statements: starting run ===")
    today = date.today()

    # Only run on the 1st — schedule lib fires daily at the given time,
    # so we gate on the calendar day
    if today.day != 1:
        logger.debug("Not the 1st of month (day=%d) — skipping statements", today.day)
        return

    try:
        from owner_statement import generate_all_statements

        output_subdir = os.path.join(OUTPUT_DIR, "owner_statements", today.strftime("%Y-%m"))
        results = generate_all_statements(output_dir=output_subdir)

        logger.info(
            "Monthly statements complete — %d statements generated in %s",
            len(results),
            output_subdir,
        )

        # Email each statement to the appropriate owner
        for result in results:
            owner_email = result.get("owner_email")
            pdf_path = result.get("pdf_path", "")
            if owner_email and pdf_path and os.path.exists(pdf_path):
                _deliver_report(
                    subject=f"Owner Statement — {result.get('property_name', 'Portfolio')} — {today.strftime('%B %Y')}",
                    pdf_path=pdf_path,
                    recipients=[owner_email, ALERT_EMAIL],
                )

    except ImportError as exc:
        logger.error("Could not import owner_statement module: %s", exc)
    except Exception as exc:
        logger.exception("Monthly owner statements failed: %s", exc)


def schedule_weekly_kpi() -> None:
    """
    Generate the weekly KPI dashboard.
    Runs every Monday at WEEKLY_KPI_TIME.
    """
    logger.info("=== Weekly KPI Dashboard: starting run ===")
    today = date.today()

    try:
        from kpi_dashboard import generate_kpi_dashboard

        output_subdir = os.path.join(OUTPUT_DIR, "kpi_dashboards")
        results = generate_kpi_dashboard(output_dir=output_subdir, persist=True)

        pdf_path = results.get("pdf_path", "")
        md_path = results.get("markdown_path", "")
        logger.info(
            "KPI dashboard complete — PDF: %s  Markdown: %s",
            pdf_path,
            md_path,
        )

        if pdf_path and os.path.exists(pdf_path):
            week_str = today.strftime("%B %d, %Y")
            _deliver_report(
                subject=f"Camelot KPI Dashboard — Week Ending {week_str}",
                pdf_path=pdf_path,
                recipients=[ALERT_EMAIL],
            )

    except ImportError as exc:
        logger.error("Could not import kpi_dashboard module: %s", exc)
    except Exception as exc:
        logger.exception("Weekly KPI dashboard failed: %s", exc)


def schedule_quarterly_update() -> None:
    """
    Generate the quarterly investor update.
    Runs on the 1st of Jan / Apr / Jul / Oct at QUARTERLY_UPDATE_TIME.
    """
    logger.info("=== Quarterly Investor Update: starting run ===")
    today = date.today()

    # Gate on: day=1 AND month in QUARTERLY_MONTHS
    if today.day != 1 or today.month not in QUARTERLY_MONTHS:
        logger.debug(
            "Not a quarterly trigger date (month=%d, day=%d) — skipping",
            today.month,
            today.day,
        )
        return

    # Determine which quarter *just ended* (prior quarter)
    # E.g. Jan 1 → report on Q4 of prior year
    quarter_map = {1: 4, 4: 1, 7: 2, 10: 3}
    report_quarter_num = quarter_map[today.month]
    report_year = today.year - 1 if today.month == 1 else today.year

    try:
        from investor_update import QuarterPeriod, generate_investor_update

        quarter = QuarterPeriod(year=report_year, quarter=report_quarter_num)
        output_subdir = os.path.join(OUTPUT_DIR, "investor_updates")
        pdf_path = generate_investor_update(quarter=quarter, output_dir=output_subdir)

        logger.info("Investor update complete — %s", pdf_path)

        if pdf_path and os.path.exists(pdf_path):
            _deliver_report(
                subject=f"Camelot Investor Update — {quarter.label}",
                pdf_path=pdf_path,
                recipients=[ALERT_EMAIL],
            )

    except ImportError as exc:
        logger.error("Could not import investor_update module: %s", exc)
    except Exception as exc:
        logger.exception("Quarterly investor update failed: %s", exc)


# ---------------------------------------------------------------------------
# Scheduler setup
# ---------------------------------------------------------------------------

def _register_jobs() -> None:
    """Register all recurring jobs with the `schedule` library."""

    # Monthly owner statements — run check daily at the configured time
    # The function itself gates on day==1
    schedule.every().day.at(MONTHLY_STATEMENTS_TIME).do(schedule_monthly_statements)
    logger.info(
        "Registered: monthly owner statements at %s (fires daily, runs on 1st)",
        MONTHLY_STATEMENTS_TIME,
    )

    # Weekly KPI dashboard — every Monday
    schedule.every().monday.at(WEEKLY_KPI_TIME).do(schedule_weekly_kpi)
    logger.info(
        "Registered: weekly KPI dashboard on Mondays at %s",
        WEEKLY_KPI_TIME,
    )

    # Quarterly investor update — daily check, function gates on date
    schedule.every().day.at(QUARTERLY_UPDATE_TIME).do(schedule_quarterly_update)
    logger.info(
        "Registered: quarterly investor update check at %s (fires 1st of quarter months)",
        QUARTERLY_UPDATE_TIME,
    )


def _handle_signal(signum: int, frame: object) -> None:
    """Graceful shutdown on SIGTERM / SIGINT."""
    logger.info("Signal %d received — shutting down scheduler", signum)
    _remove_pid()
    sys.exit(0)


def run_daemon() -> None:
    """Start the scheduler daemon and block until interrupted."""
    _ensure_dirs()
    _write_pid()
    signal.signal(signal.SIGTERM, _handle_signal)
    signal.signal(signal.SIGINT, _handle_signal)

    _register_jobs()

    logger.info(
        "Camelot Report Scheduler started — %d jobs registered",
        len(schedule.jobs),
    )
    logger.info("Next runs:")
    for job in schedule.jobs:
        logger.info("  %s → next: %s", job.job_func.__name__, job.next_run)

    try:
        while True:
            schedule.run_pending()
            time.sleep(30)  # check every 30 seconds
    except (KeyboardInterrupt, SystemExit):
        logger.info("Scheduler stopped")
        _remove_pid()


# ---------------------------------------------------------------------------
# One-shot runners (for CLI / ad-hoc execution)
# ---------------------------------------------------------------------------

def run_owner_statements_now(month_date: Optional[date] = None) -> None:
    """Immediately generate owner statements for the given month (default: today)."""
    _ensure_dirs()

    target = month_date or date.today()

    try:
        from owner_statement import generate_all_statements

        output_subdir = os.path.join(OUTPUT_DIR, "owner_statements", target.strftime("%Y-%m"))
        results = generate_all_statements(output_dir=output_subdir)
        logger.info(
            "One-shot owner statements: %d generated in %s",
            len(results),
            output_subdir,
        )
        for r in results:
            print(f"  Statement: {r.get('pdf_path', '?')}")
    except Exception as exc:
        logger.exception("One-shot owner statements failed: %s", exc)
        sys.exit(1)


def run_kpi_dashboard_now() -> None:
    """Immediately generate the KPI dashboard."""
    _ensure_dirs()

    try:
        from kpi_dashboard import generate_kpi_dashboard

        output_subdir = os.path.join(OUTPUT_DIR, "kpi_dashboards")
        results = generate_kpi_dashboard(output_dir=output_subdir, persist=True)
        print(f"Markdown: {results['markdown_path']}")
        print(f"PDF:      {results['pdf_path']}")
    except Exception as exc:
        logger.exception("One-shot KPI dashboard failed: %s", exc)
        sys.exit(1)


def run_investor_update_now(year: Optional[int] = None, quarter_num: Optional[int] = None) -> None:
    """Immediately generate the investor update for the given or current quarter."""
    _ensure_dirs()

    try:
        from investor_update import QuarterPeriod, generate_investor_update

        q: Optional[QuarterPeriod] = None
        if year and quarter_num:
            q = QuarterPeriod(year=year, quarter=quarter_num)

        output_subdir = os.path.join(OUTPUT_DIR, "investor_updates")
        pdf_path = generate_investor_update(quarter=q, output_dir=output_subdir)
        print(f"PDF: {pdf_path}")
    except Exception as exc:
        logger.exception("One-shot investor update failed: %s", exc)
        sys.exit(1)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------

if __name__ == "__main__":
    parser = argparse.ArgumentParser(
        description="Camelot OS Report Bot Scheduler",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Start the persistent daemon
  python scheduler.py --daemon

  # Run owner statements immediately
  python scheduler.py --run owner-statements

  # Run KPI dashboard immediately
  python scheduler.py --run kpi-dashboard

  # Run investor update for Q3 2025
  python scheduler.py --run investor-update --year 2025 --quarter 3
        """,
    )
    parser.add_argument(
        "--daemon",
        action="store_true",
        help="Run the persistent scheduler daemon",
    )
    parser.add_argument(
        "--run",
        choices=["owner-statements", "kpi-dashboard", "investor-update"],
        help="Run a specific report immediately (one-shot)",
    )
    parser.add_argument(
        "--year",
        type=int,
        default=None,
        help="Year for investor update (with --run investor-update)",
    )
    parser.add_argument(
        "--quarter",
        type=int,
        choices=[1, 2, 3, 4],
        default=None,
        help="Quarter for investor update (with --run investor-update)",
    )
    parser.add_argument(
        "--list-jobs",
        action="store_true",
        help="Print registered job schedule and exit",
    )

    args = parser.parse_args()

    if args.list_jobs:
        _register_jobs()
        for job in schedule.jobs:
            print(f"  {job.job_func.__name__:35s}  next: {job.next_run}")
        sys.exit(0)

    if args.daemon:
        run_daemon()
    elif args.run == "owner-statements":
        run_owner_statements_now()
    elif args.run == "kpi-dashboard":
        run_kpi_dashboard_now()
    elif args.run == "investor-update":
        run_investor_update_now(year=args.year, quarter_num=args.quarter)
    else:
        parser.print_help()
        sys.exit(1)
